# Generated by Django 4.1.4 on 2022-12-26 12:09

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('village', models.CharField(choices=[('Kas', 'Kansanga'), ('Kab', 'Kabalagala'), ('Muy', 'Muyenga'), ('Bun', 'Bunga'), ('Gga', 'Ggaba'), ('Nsa', 'Nsambya'), ('Mak', 'Makindye'), ('Buz', 'Buzinga'), ('Ebb', 'Entebbe'), ('Mun', 'Munyonyo'), ('Bus', 'Busabala'), ('Kat', 'Katwe'), ('Nti', 'Ntinda'), ('Buk', 'Bukoto'), ('Kir', 'Kireka'), ('Ban', 'Banda'), ('Nam', 'Namuwongo'), ('Kaw', 'Kawempe'), ('Gay', 'Gayaza'), ('Kr', 'Kira'), ('Nak', 'Nakasero'), ('Nkw', 'Nakawa'), ('Klo', 'Kololo')], max_length=255)),
                ('city', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('color', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=100)),
                ('body_style', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2022, 2022)], verbose_name='year')),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField()),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('wood', 'wood'), ('metalic', 'metalic'), ('plastic', 'plastic')], max_length=255)),
                ('number_seats', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
