# Generated by Django 3.0.7 on 2022-12-25 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('village', models.CharField(choices=[('Kas', 'Kansanga'), ('Kab', 'Kabalagala'), ('Muy', 'Muyenga'), ('Bun', 'Bunga'), ('Gga', 'Ggaba'), ('Nsa', 'Nsambya'), ('Mak', 'Makindye'), ('Buz', 'Buzinga'), ('Ebb', 'Entebbe'), ('Mun', 'Munyonyo'), ('Bus', 'Busabala'), ('Kat', 'Katwe'), ('Nti', 'Ntinda'), ('Buk', 'Bukoto'), ('Kir', 'Kireka'), ('Ban', 'Banda'), ('Nam', 'Namuwongo'), ('Kaw', 'Kawempe'), ('Gay', 'Gayaza'), ('Kr', 'Kira'), ('Nak', 'Nakasero'), ('Nkw', 'Nakawa'), ('Klo', 'Kololo')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('body_style', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(2022, 2022)], verbose_name='year')),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('features', models.CharField(choices=[('wood', 'wood'), ('metalic', 'metalic'), ('plastic', 'plastic')], max_length=255)),
                ('number_seats', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
