# Generated by Django 4.1.4 on 2022-12-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged')], max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='year'),
        ),
    ]
