# Generated by Django 3.0.7 on 2022-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
