# Generated by Django 3.0.7 on 2022-12-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
